---
jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
    name: Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version
      - run: pnpm add -g wrangler && pnpm i && pnpm build:web
      - id: publish
        uses: ptb/cf-pages-action@v1.6.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: ${{ vars.CLOUDFLARE_DIRECTORY }}
          environmentName: ${{ github.ref_name }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
      - uses: mydea/action-wait-for-api@main
        with:
          url: ${{ steps.publish.outputs.url }}
      - env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        id: metrics
        uses: treosh/lighthouse-ci-action@v11
        with:
          runs: 1
          temporaryPublicStorage: true
          urls: |
            ${{ steps.publish.outputs.url }}
name: Deploy
'on':
  push:
    branches:
      - develop
      - testing
      - preview
      - release
