---
jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.url }}
    name: Publish to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version
      - run: pnpm install
      # - run: pnpm build:web
      - run: pnpm install -g wrangler
      - uses: ptb/cf-pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: web
          gitHubToken: ${{ github.token }}
          projectName: gov2-us
name: Deploy
'on':
  push:
    branches:
      - testing
      - preview
      - release
