---
jobs:
  publish:
    environment:
      name: ${{ github.ref_name }}
      url: ${{ vars.CLOUDFLARE_PAGES_URL }}
    name: Publish to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: web
          projectName: gov2-us
'on': [push]
